### ISSUE TITLE
Verify correct handling of all optional fields.

### ISSUE THREAD

**Issue by kaichieh** [oasis-open/cti-taxii-client#30]
For example: If the server's API root is without description, the client will throw an exception. 
But the description is optional according to the spec, I expected there is no error here.

**Comment by gtback** [comment]
Thanks, @kaichieh. Looks like the error is coming from [here](https://github.com/oasis-open/cti-taxii-client/blob/master/taxii2client/__init__.py#L561). We correctly treat `description` as optional in the Collection and Server classes.

We should add tests to verify that the minimum set of required fields for each endpoint doesn't cause errors; I'd rather fix this type of bug globally in case there are other similar fields, rather than fixing them one-at-a-time as people discover them.
