### ISSUE TITLE
Handle invalid content better

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-taxii-client#35]
If a server (incorrectly) returns malformed data, we should at least catch the error and ensure it doesn't produce a traceback. See https://github.com/mitre/cti/issues/16

**Comment by chisholm** [comment]
Raising an exception doesn't always mean a traceback is produced.  It depends on who catches the exception and what the catcher does with it.  Exceptions can carry useful information about the nature of the error.  E.g. JSON parse error vs network error, etc.  If taxii-client just returned None to indicate error, say, that information is lost.  Would higher software layers find error information useful?  If the failing method call is part of a larger operation, I think the higher layers can often more usefully interpret/handle the error in the context of whatever it's trying to do, since they know the larger picture.  As a library, taxii-client is probably often a "lower layer", and should propagate most exceptions.

Sometimes exceptions are "chained" as they pass through library layers, so that each layer produces something more meaningful and at the appropriate level of abstraction, to the layer above.  So one avenue for improvement might be to intercept and chain a different exception, but what would be a more appropriate exception to throw in this case?  A generic "server error" of some sort?

**Comment by gtback** [comment]
I like the idea of catching the json parse error and wrapping it in some "invalid JSON returned" exception.

**Comment by clenk** [comment]
Fixed in 5bb5225.
