### ISSUE TITLE
Allow users to specify the user agent string...

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-taxii-client#40]
...and/or use a default that is specific to the taxii client.

**Comment by chisholm** [comment]
`_HTTPConnection.post()` already allows custom headers (it has a "headers" parameter).  `_HTTPConnection.get()` does not.  So there is inconsistency there.  If there is a user_agent param to the _HTTPConnection constructor, should it override the headers given in _HTTPConnection.post()?  I'm thinking not.  Perhaps a constructor param should act as a default in that case.

**Comment by chisholm** [comment]
Expanding on the above a bit: I'm unclear as to how this should behave.  E.g. you could envision four possible situations: user opts for a taxii2-client user-agent (something built-in to the library); user opts for a custom user-agent; user opts to leave it unspecified; user forces the user-agent header to not exist.  In the third situation, it looks like requests will insert its own, for example: `python-requests/2.19.1`.  Should a default taxii2client-specific user-agent be forced, so that the "requests" user-agent never appears?  Do we allow user-agent to be omitted from requests?

Btw, the format I am using is `"taxii2-client/" + __version__`, e.g. `taxii2-client/0.3.1`.  Hope that's okay.

**Comment by clenk** [comment]
I agree, _HTTPConnection.post() and .get() should be consistent and headers passed to them override any defaults set in the constructor.

IIRC, this feature request came up at the plugfest as a way to help tell who was connecting to whom. As such, I think it's okay to always send a user-agent, defaulting to a taxii2client-specific one. We can allow omitting it later if we need to.

That format looks good to me.
