### ISSUE TITLE
Behavior of "closed" session/connections

### ISSUE THREAD

**Issue by gtback** [oasis-open/cti-taxii-client#5]
I'm not sure I understand how "closing" an object (or the underlying `requests.Session`) works. 

I added a test that I expected to fail. If the session is closed, I thought subsequent web requests could not be sent. I don't fully understand the `requests` internals, but is it possibly opening new connections, and `close` just shuts all existing, open connections?

```python
@responses.activate
def test_cannot_use_closed_connection(collection):
    set_collection_response()
    collection.close()
    collection.refresh()
```

**Comment by chisholm** [comment]
I did some poking around in the `responses` code, and I think the reason you aren't seeing an error is because that library changes behavior.  In `requests`, HTTP requests through a session are eventually propagated to a back-end "adapter".  `Responses` does a sneaky surgical [replacement](https://github.com/getsentry/responses/blob/eddcb95238d49555ecfb66967b8cab9a34809755/responses.py#L449) of a key method of the HTTP adapter, which bypasses the usual connection handling.  And that means you won't see the normal connection-related errors.  So I think certain tests just won't work when `responses` is mucking around with the innards of `requests`.

**Comment by gtback** [comment]
This test is also "failing" (not raising an error for the closed session, but getting a 404 when accessing the URL) for me. `responses` shouldn't be mucking around, unless it's because it's in the same file as responses.

```python
def test_cannot_use_closed_connection():
    coll = Collection(COLLECTION_URL)
    coll.close()
    coll.refresh()
```

**Comment by chisholm** [comment]
Well, I guess closing a session doesn't invalidate it after all.  I did a test directly with requests, and there was no error.  When you close a session, it closes all adapters, which for the HTTP adapter, "clears" its connection pools, which closes all their connections and disables the pools.  So at some level, something is getting disabled.  But I guess at the next request, the adapter just makes more pools.  So if we want `_HTTPConnection` to be unusable after a close(), I guess we'll have to implement that ourselves.

**Comment by gtback** [comment]
I don't think we need to worry about explicitly making things unusable. I'm curious how commonly people will use the `close()` functionality, though I do like the context manager behavior.

**Comment by SteliosZ** [comment]
Hello. I'm trying to close a Collection connection after I make some queries, but it seems unable to. I tried to .close() then .refresh() but it seems that that connection is still up after that. 

Shouldn't this close the connection, or have I understood something wrong ?

I'm trying to create a context manager for taxii client connections, but I'm struggling as you can see. I already read the other issues but with no luck.

Thanks in advance for your time.

**Comment by chisholm** [comment]
As described above, close() does close existing connections, but it doesn't prevent subsequent connections.  refresh() sends another request, so it makes another connection.  This is just how the requests library works (at least as of 2017!  I have not looked again since then).  So it's not that the old connections haven't gone after a close(); it's just that new connections have been made.  As described above, it was not deemed important to design the taxii-client library to force failure of subsequent network operations after a close().

So your test isn't testing what you want it to.  You want to know whether there are any remaining connections after a close().  I think you will have to verify that in other ways, e.g. use OS tooling to check network connections.  Maybe try `netstat` to get a listing of TCP client connections and the remote hosts they are connected to, and see if any look like they shouldn't be there.
