### ISSUE TITLE
Question - why does the taxii client not implementing auth using api token?

### ISSUE THREAD

**Issue by bakatzir** [oasis-open/cti-taxii-client#67]
I know of a few taxii servers requiring auth using api keys.
Is there any plan to implement auth using this?
e.g: `self.my_taxii = Server(url=self.url, verify=self.verify, proxies=self.proxies, token=self.api_key)`

**Comment by kscheetz** [comment]
@bakatzir I have put in a [pull request](https://github.com/oasis-open/cti-taxii-client/pull/68) with these changes.  This will enable token-based auth as well as any other type of authentication that is usable by the requests library.

**Comment by emmanvg** [comment]
@bakatzir there were no plans to implement Token based API authentication at the time since this type of authentication is not mandated by the spec. Yet we understand different use cases and implementations may require auth methods not supported by the client and we rely on the community to also help contribute in this manner. This is often driven by interest of the community.

Thanks @kscheetz for implementing the Token based auth, you should see it in a upcoming release.
