### ISSUE TITLE
Exception in common module _grab_total_items

### ISSUE THREAD

**Issue by dcherian-dev** [oasis-open/cti-taxii-client#78]
I see the following traceback while invoking paged fetch:

```
for bundle in as_pages(collection.get_objects, per_request=50):
  File "/usr/local/lib/python2.7/dist-packages/taxii2client/v20/__init__.py", line 47, in as_pages
    total_in_request, total_available = _grab_total_items(resp)
  File "/usr/local/lib/python2.7/dist-packages/taxii2client/common.py", line 132, in _grab_total_items
    results = re.match(r"^items (\d+)-(\d+)/(\d+)$", resp.headers["Content-Range"])
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-range'
```

To fix:
- Check the key "Content-Range" before use:

```
if not resp.headers.get("Content-Range"):
     return 0, 0
```

**Comment by emmanvg** [comment]
Hi @dcherian-dev, this is likely due to a TAXII Server that does not support paged requests and you might be receiving the full response (or no objects at all) in a single request. I will make a fix to prevent this from happening, but also to let you know what might be happening in the background. Thanks for pointing this out!

**Comment by dcherian-dev** [comment]
Thanks @emmanvg for the quick response and fix!
